- name: Update APT package index
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Packages
  ansible.builtin.apt:
    name:
      - postgresql-16
      - postgresql-client-16
    state: present

- name: Disabled and stopped PostgreSQL 16 service
  ansible.builtin.systemd:
    name: postgresql
    enabled: false
    state: stopped

- name: Create PostgreSQL data directory
  ansible.builtin.file:
    path: /opt/pgsql/data
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Initialize PostgreSQL database manually
  ansible.builtin.command: >
    /usr/lib/postgresql/16/bin/initdb -D /opt/pgsql/data
  args:
    creates: /opt/pgsql/data/PG_VERSION
  become: true
  become_user: postgres

- name: Deploy postgresql.conf template
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: /opt/pgsql/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'

- name: Deploy pg_hba.conf template
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /opt/pgsql/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'

- name: Deploy postgres-custom.service template
  ansible.builtin.template:
    src: postgres-custom.service.j2
    dest: /etc/systemd/system/postgresql-custom.service
    owner: postgres
    group: postgres
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Unmask custom PostgreSQL 16 service
  ansible.builtin.command: systemctl unmask postgresql-custom
  changed_when: false

- name: Enable and start custom PostgreSQL 16 service
  ansible.builtin.systemd:
    name: postgresql-custom
    enabled: true
    state: started

- name: Wait for PostgreSQL to be ready
  ansible.builtin.wait_for:
    port: 5432
    host: 127.0.0.1
    timeout: 30

- name: Set password for postgres user if not already set
  community.postgresql.postgresql_user:
    name: postgres
    password: "{{ postgres_admin_pass }}"
    login_unix_socket: /var/run/postgresql
    login_user: postgres
  become: true
  become_user: postgres

