- name: Configure | Pre requires
  include_tasks: pre.yml
  when: inventory_hostname in groups['database']

- name: Configure | Pre requires
  include_tasks: debian.yml
  when: inventory_hostname in groups['database'] and ansible_os_family == "Debian"