- name: Install and Configure Zabbix database 
  include_tasks: database.yml
  when: inventory_hostname in groups['database'] and ansible_os_family == "Debian"

- name: Install and Configure Zabbix Server 
  include_tasks: server.yml
  when: inventory_hostname in groups['server'] and ansible_os_family == "Debian"

- name: Install and Configure Zabbix frontend 
  include_tasks: frontend.yml
  when: inventory_hostname in groups['frontend'] and ansible_os_family == "Debian"

- name: Install and Configure Zabbix proxy 
  include_tasks: proxy.yml
  when: inventory_hostname in groups['proxy'] and ansible_os_family == "Debian"

# - name: Install and Configure Grafana 
#   include_tasks: grafana.yml
#   when: inventory_hostname in groups['grafana'] and ansible_os_family == "Debian"