- name: Configure DNS in /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    marker: "# --- {mark} ZABBIX ---"
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host]['ansible_host'] }} {{ hostvars[host]['ansible_hostname'] }}.{{ domain_local }} {{ hostvars[host]['ansible_hostname'] }}
      {% endfor %}

- name: Install Packages
  ansible.builtin.apt:
    name:
      - wget
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-psycopg2
      - sudo
    state: present

- name: Install official Zabbix repository
  apt:
    deb: "{{ zabbix_repo_url }}"
    state: present

- name: Add PostgreSQL APT repository GPG key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL APT repository
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: 'pgdg'

- name: Update cache
  apt:
    update_cache: yes

- name: Change PasswordAuthentication yes in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*#?\s*PasswordAuthentication\s*(=|\s)\s*\w+'
    line: 'PasswordAuthentication yes'
    backrefs: yes
    state: present
    insertafter: EOF

- name: Change PermitRootLogin yes in sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^\s*#?\s*PermitRootLogin\s*(=|\s)\s*\w+'
    line: 'PermitRootLogin yes'
    backrefs: yes
    state: present
    insertafter: EOF

- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted